services:
  duckfolio:
    image: ghcr.io/yorlg/duckfolio:latest
    container_name: duckfolio
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - ./profile.json:/app/public/profile.json:ro
