// Known Chinese API responses mapped to locale keys.
export const adminMessageKeys: Record<string, string> = {
  "管理员口令未配置或不正确。": "invalidAdminPassword",
  "请输入有效的文章路径。": "enterAValidPostPath",
  "未配置 GitHub 写入，已阻止在本地 main 工作区删除 posts 文件。": "localPostDeleteBlocked",
  "文章不存在。": "postNotFound",
  "未配置 GitHub 写入，已阻止在本地模式下删除媒体文件。": "localMediaDeleteBlocked",
  "未配置 GitHub 写入，已阻止在本地 main 工作区创建 posts 目录。": "localPostCreateBlocked",
  "GitHub 写入失败。": "gitHubWriteFailed",
  "不允许写入该路径。": "writingToThisPathIsNotAllowed",
  "本地模式只允许保存站点配置和媒体文件。": "localWriteRestricted",
  "不允许读取该路径。": "readingFromThisPathIsNotAllowed",
  "文章列表读取失败。": "failedToLoadThePostList",
  "文章发布失败。": "failedToPublishThePost",
  "文章已设为草稿。": "postSetToDraft",
  "文章已设为公开。": "postMadePublic",
  "文章更新失败。": "failedToUpdateThePost",
  "文章已删除。": "postDeleted",
  "文章删除失败。": "failedToDeleteThePost",
  "配置保存成功。": "configurationSaveSucceeded",
  "配置保存失败。": "failedToSaveConfiguration",
  "请输入文章标题。": "enterAPostTitle",
  "文章正文不能为空。": "postBodyCannotBeEmpty",
  "旧文章路径删除失败。": "failedToDeleteTheOldPostPath",
  "文章更新成功。": "postUpdated",
  "文章发布成功。": "postPublished",
  "媒体列表读取失败。": "failedToLoadMediaList",
  "请选择要上传的文件。": "selectAFileToUpload",
  "文件不能为空。": "fileCannotBeEmpty",
  "文件不能超过 50MB。": "fileMustBe50MBOrSmaller",
  "不支持该文件类型。": "unsupportedFileType",
  "文件上传成功。": "filesUploadedSuccessfully",
  "文件上传失败。": "failedToUploadFiles",
  "请指定要删除的媒体路径。": "specifyAMediaPathToDelete",
  "媒体文件已删除。": "mediaFileDeleted",
  "媒体文件删除失败。": "failedToDeleteMediaFile",
  "请选择头像或 Logo。": "selectAnAvatarOrLogo",
  "请上传不超过 5MB 的 PNG 图片。": "uploadAPNGImageNoLargerThan5MB",
  "PNG 图片内容无效。": "invalidPNGImageContent",
  "站点图片已更新。": "siteImageUpdated",
  "站点图片上传失败。": "failedToUploadSiteImage",
  "管理员口令错误或未配置，请检查 ADMIN_PASSWORD。": "invalidAdminPasswordResponse",
  "没有权限执行该操作，请检查管理员口令。": "permissionDenied",
  "后台接口不存在，请确认部署包含 /api/admin/* 路由。": "adminApiNotFound",
  "后台接口返回了 HTML 页面而不是 JSON，请检查 Vercel 部署中的 /api/admin/* 路由。": "adminApiUnexpectedHtml"
};
